#ifndef _NETCLI_COMMANDS
#define _NETCLI_COMMANDS

// global
#define COMMAND_NONE 500
#define COMMAND_HELP 501


#define WIFI_COMMANDID_LIST 1


#define NETWORK_COMMANDID_ADAPTERS 1
#define NETWORK_COMMANDID_CONNECTIONS 2
#define NETWORK_COMMANDID_PROTOCOLS 3
#define NETWORK_COMMANDID_ROUTETABLES 4

#define RADIO_COMMANDID_WIFI 1
#define     RADIO_COMMANDID_WIFI_OFF 2
#define     RADIO_COMMANDID_WIFI_ON 3
#define     RADIO_COMMANDID_WIFI_STATUS 4
#define     RADIO_COMMANDID_WIFI_RECONNECT 5

int get_command(const char *cmd);

#endif